import os
import sqlite3
import pandas as pd

from datetime import datetime
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter


def generate_excel_report():

    # ==========================================
    # Create Reports Folder
    # ==========================================

    os.makedirs("reports", exist_ok=True)

    # ==========================================
    # Connect to Database
    # ==========================================

    connection = sqlite3.connect("stock_market.db")

    query = "SELECT * FROM stocks"

    df = pd.read_sql(query, connection)

    connection.close()

    # ==========================================
    # Check Database
    # ==========================================

    if df.empty:

        print("\nNo data found in database.")

        return

    # ==========================================
    # Company Summary
    # ==========================================

    summary = df.groupby("company_name").agg(

        Average_Closing_Price=("close_price", "mean"),

        Highest_Price=("high_price", "max"),

        Lowest_Price=("low_price", "min"),

        Average_Volume=("volume", "mean"),

        Standard_Deviation=("close_price", "std"),

        Variance=("close_price", "var")

    )

    summary = summary.round(2)

    # ==========================================
    # Output File
    # ==========================================

    output_file = "reports/Stock_Report.xlsx"

    with pd.ExcelWriter(
        output_file,
        engine="openpyxl"
    ) as writer:

        # ======================================
        # Sheet 1 : Company Summary
        # ======================================

        summary.to_excel(
            writer,
            sheet_name="Company Summary",
            startrow=4
        )

        workbook = writer.book
        worksheet = writer.sheets["Company Summary"]

        # ======================================
        # Merge Title
        # ======================================

        worksheet.merge_cells("A1:G1")

        worksheet["A1"] = "STOCK MARKET ANALYTICS REPORT"

        worksheet["A2"] = (
            "Generated On : "
            + datetime.now().strftime("%d-%m-%Y %H:%M:%S")
        )

        worksheet["A3"] = "Generated By : Ajay K"

        # ======================================
        # Title Formatting
        # ======================================

        worksheet["A1"].font = Font(
            size=20,
            bold=True,
            color="FFFFFF"
        )

        worksheet["A1"].fill = PatternFill(
            fill_type="solid",
            start_color="1F4E78",
            end_color="1F4E78"
        )

        worksheet["A1"].alignment = Alignment(
            horizontal="center",
            vertical="center"
        )

        worksheet["A2"].font = Font(italic=True)
        worksheet["A3"].font = Font(italic=True)

        # ======================================
        # Header Formatting
        # ======================================

        blue_fill = PatternFill(
            fill_type="solid",
            start_color="4F81BD",
            end_color="4F81BD"
        )

        for cell in worksheet[5]:

            cell.font = Font(
                bold=True,
                color="FFFFFF"
            )

            cell.fill = blue_fill

            cell.alignment = Alignment(
                horizontal="center",
                vertical="center"
            )

        # ======================================
        # Auto Column Width
        # ======================================

        for column in worksheet.columns:

            max_length = 0

            column_letter = get_column_letter(column[0].column)

            for cell in column:

                try:

                    if cell.value:

                        max_length = max(
                            max_length,
                            len(str(cell.value))
                        )

                except Exception:

                    pass

            worksheet.column_dimensions[column_letter].width = max_length + 4

        # ======================================
        # Sheet 2 : Stock Data
        # ======================================

        df.to_excel(
            writer,
            sheet_name="Stock Data",
            index=False
        )

        stock_sheet = writer.sheets["Stock Data"]

        for cell in stock_sheet[1]:

            cell.font = Font(
                bold=True,
                color="FFFFFF"
            )

            cell.fill = blue_fill

            cell.alignment = Alignment(horizontal="center")

        for column in stock_sheet.columns:

            max_length = 0

            column_letter = get_column_letter(column[0].column)

            for cell in column:

                try:

                    if cell.value:

                        max_length = max(
                            max_length,
                            len(str(cell.value))
                        )

                except Exception:

                    pass

            stock_sheet.column_dimensions[column_letter].width = max_length + 4

        # ======================================
        # Sheet 3 : Executive Dashboard
        # ======================================

        dashboard = pd.DataFrame({

            "Metric":[

                "Total Companies",

                "Total Records",

                "Highest Stock Price",

                "Lowest Stock Price",

                "Average Closing Price",

                "Highest Volume Company",

                "Lowest Volume Company",

                "Report Generated On"

            ],

            "Value":[

                df["company_name"].nunique(),

                len(df),

                round(df["high_price"].max(),2),

                round(df["low_price"].min(),2),

                round(df["close_price"].mean(),2),

                df.groupby("company_name")["volume"].sum().idxmax(),

                df.groupby("company_name")["volume"].sum().idxmin(),

                datetime.now().strftime("%d-%m-%Y %H:%M:%S")

            ]

        })

        dashboard.to_excel(
            writer,
            sheet_name="Executive Dashboard",
            index=False
        )

        dashboard_sheet = writer.sheets["Executive Dashboard"]

        for cell in dashboard_sheet[1]:

            cell.font = Font(
                bold=True,
                color="FFFFFF"
            )

            cell.fill = blue_fill

            cell.alignment = Alignment(horizontal="center")

        for column in dashboard_sheet.columns:

            max_length = 0

            column_letter = get_column_letter(column[0].column)

            for cell in column:

                try:

                    if cell.value:

                        max_length = max(
                            max_length,
                            len(str(cell.value))
                        )

                except Exception:

                    pass

            dashboard_sheet.column_dimensions[column_letter].width = max_length + 4

    # ======================================
    # Success Message
    # ======================================

    print("\n" + "=" * 60)
    print("EXCEL REPORT GENERATED SUCCESSFULLY")
    print("=" * 60)

    print(f"\nSaved Location : {output_file}")

    print("\nReport Includes:")

    print("1. Company Summary")

    print("2. Stock Data")

    print("3. Executive Dashboard")
